#!/usr/bin/env bash
# Scales Django app, monitors pods, load tests, resource usage

kubectl scale deployment django-messaging-app --replicas=3

kubectl get pods

wrk -t12 -c400 -d30s http://your-app-url/

kubectl top pods
