apiVersion: v1
kind: Service
metadata:
  name: messaging-service
spec:
  selector:
    app: messaging
    color: blue  # or green, update when switching traffic
  ports:
  - port: 8000
    targetPort: 8000
